//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schedule.RecursosTextos {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Schedule.RecursosTextos.Global", typeof(Global).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a and.
        /// </summary>
        internal static string and {
            get {
                return ResourceManager.GetString("and", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a at.
        /// </summary>
        internal static string at {
            get {
                return ResourceManager.GetString("at", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a between.
        /// </summary>
        internal static string between {
            get {
                return ResourceManager.GetString("between", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a day.
        /// </summary>
        internal static string day {
            get {
                return ResourceManager.GetString("day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a days.
        /// </summary>
        internal static string days {
            get {
                return ResourceManager.GetString("days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a every.
        /// </summary>
        internal static string every {
            get {
                return ResourceManager.GetString("every", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Occurs {0} {1} between {2} starting on {3}.
        /// </summary>
        internal static string ExitRecurring {
            get {
                return ResourceManager.GetString("ExitRecurring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a hour.
        /// </summary>
        internal static string hour {
            get {
                return ResourceManager.GetString("hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a hours.
        /// </summary>
        internal static string hours {
            get {
                return ResourceManager.GetString("hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a months.
        /// </summary>
        internal static string months {
            get {
                return ResourceManager.GetString("months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a of.
        /// </summary>
        internal static string of {
            get {
                return ResourceManager.GetString("of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a on.
        /// </summary>
        internal static string on {
            get {
                return ResourceManager.GetString("on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a once.
        /// </summary>
        internal static string once {
            get {
                return ResourceManager.GetString("once", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Occurs {0}. Schedule will be used on {1}.
        /// </summary>
        internal static string Output {
            get {
                return ResourceManager.GetString("Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a starting on {0}.
        /// </summary>
        internal static string StartingOn {
            get {
                return ResourceManager.GetString("StartingOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a the.
        /// </summary>
        internal static string the {
            get {
                return ResourceManager.GetString("the", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Need to fill the configuration.
        /// </summary>
        internal static string ValidateConfiguration {
            get {
                return ResourceManager.GetString("ValidateConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Need to set Daily Frequency.
        /// </summary>
        internal static string ValidateDailyFrequency {
            get {
                return ResourceManager.GetString("ValidateDailyFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Need to set the Date From and Step in configuration.
        /// </summary>
        internal static string ValidateDateConfiguration {
            get {
                return ResourceManager.GetString("ValidateDateConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Need to set any day in weekly configuration.
        /// </summary>
        internal static string ValidateDayWeekSelected {
            get {
                return ResourceManager.GetString("ValidateDayWeekSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hour From not should be bigger than Hour To.
        /// </summary>
        internal static string ValidateHourFromBigggerHourTo {
            get {
                return ResourceManager.GetString("ValidateHourFromBigggerHourTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hour step must be bigger than 0.
        /// </summary>
        internal static string ValidateHourStep {
            get {
                return ResourceManager.GetString("ValidateHourStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Need to set hour step in daily frequency bigger than 0.
        /// </summary>
        internal static string ValidateHourStepOfDailyFrequency {
            get {
                return ResourceManager.GetString("ValidateHourStepOfDailyFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Need to set one of the checks in Monthly Configuration (day, the ..).
        /// </summary>
        internal static string ValidateMonthlyConfiguration {
            get {
                return ResourceManager.GetString("ValidateMonthlyConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Need to set month(s) bigger than 0.
        /// </summary>
        internal static string ValidateMonthlyMonths {
            get {
                return ResourceManager.GetString("ValidateMonthlyMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Need to set the hour from and hour to.
        /// </summary>
        internal static string ValidateMonthlyMoreHourFromTo {
            get {
                return ResourceManager.GetString("ValidateMonthlyMoreHourFromTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Need to set the day frequency.
        /// </summary>
        internal static string ValidateMonthlyMoreWeekStep {
            get {
                return ResourceManager.GetString("ValidateMonthlyMoreWeekStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Day must be bigger than 0.
        /// </summary>
        internal static string ValidateMonthlyOnceDayFrequency {
            get {
                return ResourceManager.GetString("ValidateMonthlyOnceDayFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Month must be bigger than 0.
        /// </summary>
        internal static string ValidateMonthlyOnceMonthFrequency {
            get {
                return ResourceManager.GetString("ValidateMonthlyOnceMonthFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Need to set when occurs recurring.
        /// </summary>
        internal static string ValidateRecurringFrequency {
            get {
                return ResourceManager.GetString("ValidateRecurringFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Week step must be bigger than 0.
        /// </summary>
        internal static string ValidateWeeklyStep {
            get {
                return ResourceManager.GetString("ValidateWeeklyStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a weeks.
        /// </summary>
        internal static string weeks {
            get {
                return ResourceManager.GetString("weeks", resourceCulture);
            }
        }
    }
}
